from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
import os

def generate_forensic_report(output_path: str, document_data: dict) -> str:
    """
    Generates a professional forensic audit report PDF.
    """
    doc = SimpleDocTemplate(output_path, pagesize=letter)
    styles = getSampleStyleSheet()
    elements = []

    # Title
    title_style = ParagraphStyle(
        'ForensicTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor("#3b82f6"),
        spaceAfter=30
    )
    elements.append(Paragraph("FORENSIC VERIFICATION REPORT", title_style))
    elements.append(Spacer(1, 12))

    # Summary Table
    data = [
        ["Document ID", document_data.get("id", "N/A")],
        ["Filename", document_data.get("filename", "N/A")],
        ["Final Verdict", document_data.get("verdict", "N/A")],
        ["Confidence Score", f"{document_data.get('confidence', 0) * 100:.2f}%"],
        ["Analysis Date", document_data.get("created_at", "N/A")]
    ]
    
    table = Table(data, colWidths=[150, 300])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor("#f1f5f9")),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor("#cbd5e1"))
    ]))
    elements.append(table)
    elements.append(Spacer(1, 40))

    # AI Findings
    elements.append(Paragraph("AI FINDINGS & ANOMALIES", styles['Heading2']))
    elements.append(Spacer(1, 12))
    
    findings = document_data.get("findings", [])
    if findings:
        for finding in findings:
            elements.append(Paragraph(f"• <b>{finding['label']}</b>: {finding.get('desc', 'Inconsistency detected.')}", styles['Normal']))
    else:
        elements.append(Paragraph("No significant structural anomalies detected.", styles['Normal']))

    elements.append(Spacer(1, 40))
    
    # Disclaimer
    disclaimer_style = ParagraphStyle('Disclaimer', fontSize=8, textColor=colors.grey)
    elements.append(Paragraph("CONFIDENTIAL: This report is generated by AL Authenticator. It is intended for institutional use only and should be cross-referenced with human analysis.", disclaimer_style))

    doc.build(elements)
    return output_path
